browser=chrome
base.url=file:///C:/Users/deepi/Downloads/preview.html

implicit.wait=0
explicit.wait=10
page.load.timeout=10

headless=false
screenshot.dir=test-output/screenshots
report.dir=test-output/ExtentReport.html